set nocompatible              " be iMproved, required
filetype off                  " required
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1
let $FZF_DEFAULT_COMMAND = 'fd --hidden --follow --exclude .git'
let mapleader = " "
syntax on 

" =================

" == Options ==

set clipboard=unnamedplus

set autoindent

" tabs & indent
set tabstop=2
set shiftwidth=2 smarttab
set expandtab

" lines
set scrolloff=999
set number
set relativenumber
set wrap
set linebreak

" backspace
set backspace=indent,eol,start

" split windows
set splitright
set splitbelow

" =================

" == Keymaps ==

nmap <C-s> :wa<CR>

" Tabs and splits
nmap <leader>tn :tabnew<CR>
nmap <leader>sv :vsp<CR>
nmap <leader>sh :sp<CR>

" Window resizing
nmap = :vertical resize +5<CR>
nmap - :vertical resize -5<CR>
nmap + :horizontal resize +2<CR>
nmap _ :horizontal resize -2<CR>

" Window navigation
nmap <leader>wh <C-w>h
nmap <leader>wj <C-w>j
nmap <leader>wk <C-w>k
nmap <leader>wl <C-w>l

" Tab navigation
nmap <S-l> gt
nmap <S-h> gT

" Fuzzy finder
nmap <leader>ff :Files .<CR> 
nmap <leader>fg :GFiles<CR> 

" Lazygit
nmap <leader>gg :!lazygit<CR><CR>

" =================
