" === Options ===
let mapleader = " "

filetype plugin indent on
syntax enable 
highlight VertSplit cterm=NONE

set noswapfile
set incsearch
set clipboard=unnamedplus
set textwidth=80

set tabstop=2
set shiftwidth=2 smarttab
set expandtab
set smartindent

set scrolloff=8
set number
set relativenumber
set linebreak

set backspace=indent,eol,start

set splitright
set splitbelow

" === Keymaps ===
nnoremap <C-s> <cmd>wa<cr>
nnoremap <leader>rn <cmd>%s/\<<C-r><C-w>\>//g<Left><Left><cr>
nnoremap <C-t> <cmd>term<cr>

nnoremap <leader>tn <cmd>tabnew<cr>
nnoremap <leader>sv <cmd>vsp<cr>
nnoremap <leader>sh <cmd>sp<cr>

nnoremap = <cmd>vertical resize +5<cr>
nnoremap - <cmd>vertical resize -5<cr>
nnoremap + <cmd>horizontal resize +2<cr>
nnoremap _ <cmd>horizontal resize -2<cr>

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

nnoremap <S-l> gt
nnoremap <S-h> gT

nnoremap <leader>e :Ex<CR> 
